name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker build \
            -t sanjaygovinds44/containerized-app:latest \
            -t ghcr.io/sanjay723/containerized-app:latest .
          docker push sanjaygovinds44/containerized-app:latest
          docker push ghcr.io/sanjay723/containerized-app:latest

      - name: Deploy Container
        run: |
          docker stop web-app || true
          docker rm web-app || true
          docker run -d -p 3000:3000 --name web-app ghcr.io/sanjay723/containerized-app:latest 
