name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t containerized-app:latest .
      - name: Deploy Container
        run: |
          docker stop web-app || true
          docker rm web-app || true
          docker run -d -p 3000:3000 --name web-app containerized-app:latest          
